- apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:otto-kesselgulasch/gimp'
    - 'ppa:libreoffice/libreoffice-5-4'
- name: install gui app 2nd
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - gimp
    - gimp-gmic
    - libreoffice
    - goldendict
    - vlc
    - freeplane
    - playonlinux

# 2018.09.11.install_Synergy
#sudo apt-get install libxtst-dev qtbase5-dev libavahi-compat-libdnssd-dev cmake
#tclsh ;
#set p synergy-core ;
#set d $env(HOME)/Downloads/${p} ;
#exec >&@stdout git clone https://github.com/symless/${p}.git ;
#cd ${p} ;
#git checkout -b v1.10.0-stable v1.10.0-stable ;
#mkdir build ;
#cd build ;
#cmake -DCMAKE_INSTALL_PREFIX=${d} .. ;
#make ;
#make install ;

# image viewer
# https://skalldan.wordpress.com/2011/09/02/ubuntu-%E3%81%A7%E8%BB%BD%E9%87%8F%E3%81%AE%E7%94%BB%E5%83%8F%E3%83%93%E3%83%A5%E3%83%BC%E3%82%A2-feh-%E3%82%92%E4%BD%BF%E3%81%86/
# apt-get install libcurl4-openssl-dev libx11-dev libxt-dev libimlib2-dev libxinerama-dev libjpeg-progs
# wget -O - 'http://feh.finalrewind.org/feh-2.27.1.tar.bz2' | tar xjf -
# cd feh-2.27.1
# make
# sudo make install

#- apt_repository:
#    repo: 'maarten-baert/simplescreenrecorder'
#- name: install gui app
#  apt: name={{item}}
#  with_items:
#    - simplescreenrecorder
#    - simplescreenrecorder-lib
