- name: GitLab install
  become: yes
  become_user: root
  shell: curl -f https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml > {{ HOME }}/docker-compose.yml

- git:
    become: yes
    become_user: root
    #repo: git://github.com/enxajt/docker-gitlab.git
    repo: ssh://git@github.com/enxajt/docker-gitlab.git
    dest: ~/.dotfiles 
    accept_hostkey: yes
