- name: ubuntu desktop before user
  hosts: localhost
  user: vagrant
  become: true
  tasks:
    #    refer list in Japan
    #    - name: change mirror
    #      become: yes
    #      replace: |
    #        dest=/etc/apt/sources.list
    #        regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
    #        replace=http://ftp.riken.go.jp/Linux/ubuntu\2
    #      register: apt_mirror
    #    - name: apt update
    #      become: yes
    #      apt: update_cache=yes
    #      when: apt_mirror|changed
 
    - name: install aptitude
      apt: name=aptitude
      become: yes

    - name: add apt-key JapTeam package repository
      shell: wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | apt-key add -
    - name: add apt-key JapTeam package repository
      shell: wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | apt-key add -
    - name: add apt-key JapTeam package repository
      shell: wget https://www.ubuntulinux.jp/sources.list.d/trusty.list -O /etc/apt/sources.list.d/ubuntu-ja.list

    - name: updates a server
      apt: update_cache=yes
    - name: upgrade a server
      apt: upgrade=full

    #- name: install japanese
    #  apt: name={{item}}
    #  become: yes
    #  with_items:
        #- language-pack-ja
        #- ubuntu-defaults-ja # JapTeam package repository
        #- fcitx-mozc
        #- fcitx-libs-qt5
        #- fcitx-frontend-qt5
        #- im-setup-helper
        # fcitxと入力、表示されたFcitxセットアップヘルパーをクリックして起動する。
        # ダイアログが表示され、Fcitxをデフォルトにする設定を行いますか？
        #「はい」ボタンをクリック、「OK」ボタンをクリックして設定を終了
        # Ubuntuを再起動する。
        # mozcと入力、表示されたMozc の設定をクリックして起動
        # 「辞書」タブをクリック、「ユーザ辞書の編集...」ボタンをクリック、辞書ツールが起動
        # 「管理」ボタンをクリックして新規辞書にインポート...などから辞書ファイルを読み込む

    - name: install nkf
      apt: name={{item}}
      become: yes
      with_items:
        #- language-pack-ja
        - nkf

    - name: install zsh
      apt: name={{item}}
      become: yes
      with_items:
        - zsh
    - name: get zshrc
      get_url:
        url: https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc
        dest: ~/.zshrc
    - name: chsh to zsh
      shell: chsh -s /bin/zsh

    - name: mkdir kohei-dev
      file: path=~/kohei-dev state=directory owner=root group=root mode=0777
    - name: get Dockerfile
      get_url:
        url: https://raw.githubusercontent.com/enxajt/dockerfiles/master/vim-ubuntu/Dockerfile
        dest: ~/kohei-dev/Dockerfile 
    - name: nkf Dockerfile
      shell: nkf -w -Lu --overwrite ~/kohei-dev/Dockerfile
    
    - git_config:
        name: user.name
        scope: global
        value: 'enxajt' 
    - git_config:
        name: user.email
        scope: global
        value: 'enxajt@gmail.com' 
    
    - name: install ubuntu-desktop
      apt: name={{item}}
      become: yes
      with_items:
        - ubuntu-desktop
    
    - name: reboot
      command: shutdown -r now
