---
- name: ubuntu desktop
  hosts: localhost
  user: vagrant
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  roles:
    #- apt-in-Japan

    - cui-app      
    - dotfiles
    - docker-inst

    - gui-app
    - japanese
    - end
    - reboot
