---
- name: ubuntu desktop
  hosts: localhost
  user: vagrant
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  roles:
    - for-all-users

    - make-user
    - for-each-user
    - dotfiles
    - docker-inst

    - desktop
    - japanese
