- name: ubuntu desktop
  hosts: localhost
  user: vagrant
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  tasks:
    #    refer list in Japan
    #    - name: change mirror
    #      become: yes
    #      replace: |
    #        dest=/etc/apt/sources.list
    #        regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
    #        replace=http://ftp.riken.go.jp/Linux/ubuntu\2
    #      register: apt_mirror
    # 
    #    - name: apt update
    #      become: yes
    #      apt: update_cache=yes
    #      when: apt_mirror|changed
 
    # - name: install aptitude
    #   apt: name=aptitude
    #   become: yes

    # - name: updates a server
    #   apt: update_cache=yes
    # - name: upgrade a server
    #   apt: upgrade=full
    # 
    # - name: install apt packages
    #   apt: name={{item}}
    #   become: yes
    #   with_items:
    #     #- language-pack-ja
    #     - ubuntu-desktop
    #     - nkf
    #     - zsh
    
    - name: user
      user: name="{{ ubuntu_user }}" password="{{ ubuntu_pass }}" shell=/bin/zsh state=present append=yes groups=sudo
    
    - name: zshrc
      become: yes
      become_user: "{{ ubuntu_user }}"
      get_url:
        url: https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc
        dest: ~/.zshrc
    
    - name: mkdir kohei-dev
      file: path=~/kohei-dev state=directory owner="{{ ubuntu_user }}" group="{{ ubuntu_user }}" mode=0777
    
    - name: Dockerfile
      become: yes
      become_user: "{{ ubuntu_user }}"
      get_url:
        url: https://raw.githubusercontent.com/enxajt/dockerfiles/master/vim-ubuntu/Dockerfile"
        dest: ~/kohei-dev/Dockerfile \
    
    - git_config:
        name: user.name
        scope: global
        value: 'enxajt' 
    
    - git_config:
        name: user.email
        scope: global
        value: 'enxajt@gmail.com' 
    
    - name: reboot
      command: shutdown -r now
