- name: ubuntu
  user: vagrant
  become: true
  hosts: 127.0.0.1
  connection: local
  vars:
    USER: enxajt
  tasks:
    #    refer list in Japan
    #    - name: change mirror
    #      become: yes
    #      replace: |
    #        dest=/etc/apt/sources.list
    #        regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
    #        replace=http://ftp.riken.go.jp/Linux/ubuntu\2
    #      register: apt_mirror
    # 
    #    - name: apt update
    #      become: yes
    #      apt: update_cache=yes
    #      when: apt_mirror|changed
 
    - name: install aptitude
      become: yes
      apt: name=aptitude

    - name: updates a server
      apt: update_cache=yes
    - name: upgrade a server
      apt: upgrade=full
    
    - name: install apt packages
      become: yes
      apt: name={{item}}
      with_items:
        #- language-pack-ja
        - ubuntu-desktop
        - nkf
        - zsh
    
    - name: user
      shell: useradd -m USER \
        && gpasswd -a enxajt sudo \
        && chsh -s /usr/bin/zsh enxajt
    
    - name: Dockerfile
      shell: su enxajt \
        && curl https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc > ~/.zshrc \
        && mkdir ~/kohei-dev \
        && curl "https://raw.githubusercontent.com/enxajt/dockerfiles/master/vim-ubuntu/Dockerfile" > ~/kohei-dev/Dockerfile \
        && nkf -w -Lu --overwrite Dockerfile \
    
    - name: git config
      shell: git config --global user.email "enxajt@gmail.com" \
        && git config --global user.name "enxajt" \
        
    - name: zshrc
      shell: curl https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc > ~/.zshrc \
    
    - name: reboot
      shell: sudo reboot
