---
- name: ubuntu desktop
  hosts: localhost
  user: vagrant
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  roles:
    # - basic
    # - user
    # - desktop
    - autostart
    #- git
    #- docker-inst
    #- jap
    #
    #virtualbox共有ディレクトリがある場合、vagrant reload だけでいいのでは
    #- reboot
