---
- name: ubuntu desktop
  hosts: localhost
  user: vagrant
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  roles:
    - basic
    - user
    # - git
    #- jap
    #- docker-inst
    #- desktop
    - reboot
    #- autostart
    #- test
