- name: ubuntu
#remote_user: vagrant
  su: True
  su_user: root
  hosts: localhost
  connection: local
  vars:
    USER: enxajt
  tasks:
    - name: Hello.txt
      shell: echo Hello world! > hello.txt

    #    # パッケージの一覧を取得するサーバを、日本のサーバに変更
    #    - name: change mirror
    #      become: yes
    #      replace: |
    #        dest=/etc/apt/sources.list
    #        regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
    #        replace=http://ftp.riken.go.jp/Linux/ubuntu\2
    #      register: apt_mirror
    # 
    #    - name: apt update
    #      become: yes
    #      apt: update_cache=yes
    #      when: apt_mirror|changed
 
    - name: install apt packages
      become: yes
      apt: name={{item}}
      with_items:
        #- language-pack-ja
        - ubuntu-desktop
        - nkf
        - zsh

    - name: user
      shell: useradd -m USER \
        && gpasswd -a enxajt sudo \
        && chsh -s /usr/bin/zsh enxajt

    - name: Dockerfile
      shell: su enxajt \
        && curl https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc > ~/.zshrc \
        && mkdir ~/kohei-dev \
        && curl "https://raw.githubusercontent.com/enxajt/dockerfiles/master/vim-ubuntu/Dockerfile" > ~/kohei-dev/Dockerfile \
        && nkf -w -Lu --overwrite Dockerfile \

    - name: reboot
      shell: sudo reboot
