---
- name: ubuntu desktop
  hosts: localhost
  user: vagrant
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  roles:
    - basic
    - user
    - jap
    - docker-inst
    - desktop
