---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  vars:
    ubuntu_user: 
    ubuntu_pass: 
    git_user: 
    git_email:
  #vars_prompt:
  #  - name: ubuntu_user
  #    prompt: "input ubuntu_user."
  #    private: no
  #  - name: ubuntuo_pass
  #    prompt: "input ubuntu_pass."
  #    private: no
  #  - name: git_user
  #    prompt: "input git_user.   "
  #    private: no
  #  - name: git_email
  #    prompt: "input git_email.  "
  #    private: no
  roles:
    - apt-in-Japan
    - dot-config
    - cui-app
    - gui-app
    - config

    #- hardware

    #- npm
    #- xfce4-terminal
    #- gui-app-2nd
    #- bluetooth
    #- printer_pine64
    #- ebook
    #- dropbox
    #- go
    #- ghq
    #- docker-inst
    #- clamav

    - japanese
    #- long
    - end
