---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
    mail: enxajt@gmail.com
  roles:
    - apt-in-Japan
    
    - cui-app
    #- bluetooth
    - gui-app
    #- printer_pine64
    #- ebook
    - dot-config
    - config

    #- go
    #- ghq

    - docker-inst
    - japanese
    #- long
    - end
