---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  # vars:
  #   ubuntu_user: enxajt
  #   ubuntu_pass: enxajt
  #   email: enxajt@gmail.com
  vars_prompt:
    - name: ubuntu_user
      prompt: "input ubuntu_user."
      private: no
    - name: ubuntu_pass
      prompt: "input ubuntu_pass."
      private: no
    - name: git_user
      prompt: "input git_user."
      private: no
    - name: git_email
      prompt: "input git_email."
      private: no

  roles:
    - apt-in-Japan
    
    - dot-config
    - cui-app
    #- bluetooth
    - gui-app
    #- printer_pine64
    #- ebook
    - config

    #- go
    #- ghq

    - docker-inst
    - japanese
    #- long
    - end
