---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  vars:
    ubuntu_user: enxajt
    ubuntu_pass: enxajt
  roles:
    - cui-app
    - gui-app
    - dotfiles
    - config

    - go
    - ghq

    - docker-inst
    - japanese
    - long
    - reboot
