---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  vars:
    ubuntu_user: hinako
    ubuntu_pass: hinako
    mail: baihinato@gmail.com
  roles:
    - apt-in-Japan
    
    - cui-app
    # - bluetooth
    - gui-app
    - dot-config
    - config

    - go
    - ghq

    - docker-inst
    - japanese
    #- long
    - end
