---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  vars:
     git_user: enxajt
  vars_prompt:
    - name: ubuntu_user
      prompt: "input ubuntu_user"
      private: no
    # # for make_user
    # - name: ubuntu_password
    #   prompt: "input ubuntu_password"
    #   private: no
    - name: git_email
      prompt: "input git_email"
      private: no
  roles:
    - localize

    # - make-user
    - dot-config
    - cui-app
    # - cui-app-2nd
    - dropbox

    - gui-app
    # - gui-app-2nd

    # - hardware
    # - hardware-2nd

    # - ebook
    # - npm
    # - docker-inst
    # - docker-build

    # - xfce4-terminal
    # - go
    # - ghq
    # - mate
    # - plantuml
    # - gitlab
    # - printer_pine64
    # - av
    # - clamav

    - japanese
    - end
