---
- name: local ubuntu desktop
  hosts: localhost
  become: true
  vars:
    ubuntu_user: enxajt
    git_user: enxajt
  #vars_prompt:
    # # for make_user
    # - name: ubuntu_password
    #   prompt: "input ubuntu_password."
    #   private: no
    - name: git_email
      prompt: "input git_email.  "
      private: no
  roles:
    # - make-user
    - apt-in-Japan
    - dot-config
    - cui-app
    #- cui-app-2nd
    - dropbox
    - config

    - gui-app
    # - gui-app-2nd
    # - ebook
    # - hardware
    # - hardware-2nd
    # - bluetooth

    # XPS13
    # - docker-inst
    # - npm

    # - xfce4-terminal
    # - go
    # - ghq
    # - printer_pine64
    # - clamav

    - japanese
    - end
