- name: clone .config
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/enxajt/.config.git
    dest: /home/{{ ubuntu_user }}/config 
    accept_hostkey: yes
- shell: |
    cd /home/{{ ubuntu_user }}/.config && git remote set-url origin git@github.com:enxajt/.config.git

- user:
    name: "{{ ubuntu_user }}"
    shell: /bin/zsh
- file:
    src: /home/{{ ubuntu_user }}/.config/zsh/zshrc
    dest: /home/{{ ubuntu_user }}/.zshrc
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- name: clone zsh-git-prompt
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/olivierverdier/zsh-git-prompt.git
    dest: /home/{{ ubuntu_user }}/.config/zsh-git-prompt
    accept_hostkey: yes

- name: clone tmux-plugins
  git:
    repo: git://github.com/tmux-plugins/tpm.git
    dest: /home/{{ ubuntu_user }}/.config/tmux/plugins/tpm 
    accept_hostkey: yes

- file:
    path: /usr/share/lightdm/lightdm.conf.d
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.config/desktop/60-lightdm-gtk-greeter.conf
    dest: /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
    state: link
    force: yes
- file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory
- name: Xresources
  file:
    src: /home/{{ ubuntu_user }}/.config/Xresources
    dest: /etc/lightdm/lightdm.conf.d/.Xresources
    state: link

- name: xbindkeysrc
  file:
    src: /home/{{ ubuntu_user }}/.config/xbindkeysrc
    dest: /home/{{ ubuntu_user }}/.xbindkeysrc
    state: link

- name: init-xdg after clone .config
  shell: |
    sh /home/{{ ubuntu_user }}/init/init-xdg.sh
