- name: clone .config
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/enxajt/.config.git
    dest: "/home/{{ ubuntu_user }}/.config"
    accept_hostkey: yes
    force: yes
- shell: |
    cd /home/"{{ ubuntu_user }}"/.config && git remote set-url origin git@github.com:enxajt/.config.git

- user:
    name: "{{ ubuntu_user }}"
    shell: /bin/zsh
- file:
    src: "/home/{{ ubuntu_user }}/.config/zsh/zshrc"
    dest: "/home/{{ ubuntu_user }}/.zshrc"
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- name: clone zsh-git-prompt
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/olivierverdier/zsh-git-prompt.git
    dest: "/home/{{ ubuntu_user }}/.config/zsh-git-prompt"
    accept_hostkey: yes

- name: clone tmux-plugins
  git:
    repo: git://github.com/tmux-plugins/tpm.git
    dest: "/home/{{ ubuntu_user }}/.config/tmux/plugins/tpm"
    accept_hostkey: yes

- file:
    path: /usr/share/lightdm/lightdm.conf.d
    state: directory
- file:
    src: "/home/{{ ubuntu_user }}/.config/desktop/60-lightdm-gtk-greeter.conf"
    dest: /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
    state: link
    force: yes

- file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory
- name: Xresources
  file:
    src: "/home/{{ ubuntu_user }}/.config/Xresources"
    dest: /etc/lightdm/lightdm.conf.d/.Xresources
    state: link

- name: xbindkeysrc
  file:
    src: "/home/{{ ubuntu_user }}/.config/xbindkeysrc"
    dest: "/home/{{ ubuntu_user }}/.xbindkeysrc"
    state: link

- name: neovim,xdg clone init 
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/enxajt/init.git
    dest: "/home/{{ ubuntu_user }}/init"
- name: neovim,xdg git remote set-url origin git@github.com:enxajt/init.git
  shell: |
    cd /home/{{ ubuntu_user }}/init && git remote set-url origin git@github.com:enxajt/init.git
- name: install-neovim.sh
  become: true
  become_user: "{{ ubuntu_user }}" 
  shell: | 
    #sh "/home/{{ ubuntu_user }}/init/install-neovim.sh"
- name: init-xdg after clone .config
  shell: |
    sh "/home/{{ ubuntu_user }}/init/init-xdg.sh"
- name: Removing
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ ubuntu_user }}/init"

- name: neovim apt-get
  apt: name={{item}}
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
- name: neovim apt-get
  apt: name={{item}}
  with_items:
    - software-properties-common
- apt_repository:
    repo: "{{ item }}"
  with_items: 
    - 'ppa:neovim-ppa/stable'

- name: apt update
  apt: update_cache=yes
  when: apt_mirror|changed
- name: neovim apt-get
  apt: name={{item}}
  with_items:
    - neovim

- name: npm install apt-get
  apt: name={{item}}
  with_items:
    - build-essential
    - nodejs
    - npm
# if npm -v doesn't work, restart shell
- name: npm install n
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - n
- name: npm install
  shell: |
    sudo n stable
    sudo ln -sf /usr/local/bin/node /usr/bin/node
    sudo apt-get -y purge nodejs npm
    npm update
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- name: npm install apt-get
  apt: name={{item}}
  with_items:
    - nodejs

- name: tmux install apt-get
  apt: name={{item}}
  with_items:
    - automake 
    - libevent-dev 
    - libncurses5-dev
    - xsel
    - pkg-config
- name: tmux install clone
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/tmux/tmux
    dest: "/home/{{ ubuntu_user }}/.cache/tmux"
    accept_hostkey: yes
    update: yes
    force: yes
- name: tmux install
  vars:
    path_tmux: "/home/{{ ubuntu_user }}/.cache/tmux"
  shell: |
    cd {{ path_tmux }} && sh autogen.sh
    cd {{ path_tmux }} && ./configure
    #cd {{ path_tmux }} && make -j4
    cd {{ path_tmux }} && make
    cd {{ path_tmux }} && sudo make install
