- name: clone .config
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: https://github.com/enxajt/.config.git
    dest: "/home/{{ ubuntu_user }}/.config"
    accept_hostkey: yes
    force: yes

- user:
    name: "{{ ubuntu_user }}"
    shell: /bin/zsh
- file:
    src: "/home/{{ ubuntu_user }}/.config/zsh/zshrc"
    dest: "/home/{{ ubuntu_user }}/.zshrc"
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- name: mkdir -p /home/{{ ubuntu_user }}/.local/share/Trash/files
  become: yes
  become_user: "{{ ubuntu_user }}" 
  shell: |
    mkdir -p /home/{{ ubuntu_user }}/.local/share/Trash/files

- name: clone zsh-git-prompt
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: https://github.com/zsh-git-prompt/zsh-git-prompt.git
    dest: "/home/{{ ubuntu_user }}/.config/zsh-git-prompt"
    accept_hostkey: yes

- name: clone tmux-plugins
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "/home/{{ ubuntu_user }}/.config/tmux/plugins/tpm"
    accept_hostkey: yes
