- name: make sure we have a 'wheel' group
  become: yes
  become_user: root
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
- name: add user to wheel group
  become: yes
  become_user: root
  user: name="{{ ubuntu_user }}" password="{{ 'enxajt'|password_hash('sha512') }}" shell=/bin/zsh state=present append=yes groups=wheel

- name: zshrc
  become: yes
  become_user: "{{ ubuntu_user }}"
  get_url:
    url: https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc
    dest: ~/.zshrc

- name: xterm
  become: yes
  become_user: "{{ ubuntu_user }}"
  get_url:
    url: https://raw.githubusercontent.com/enxajt/xterm/master/.Xresources
    dest: ~/.Xresources

### heavy 
- name: install ubuntu-desktop
  apt: name={{item}}
  become: yes
  with_items:
    - ubuntu-desktop

- name: reboot
  become: yes
  become_user: root
  command: shutdown -r now
