- name: install ubuntu-desktop
  apt: name={{item}}
  become: yes
  with_items:
    - ubuntu-desktop
    - wmctrl

# 初期設定ではキーボードの設定が一部リセットされる場合があるので設定を変更
- name: keyboard setting
  shell: gsettings set org.gnome.settings-daemon.plugins.keyboard active false
