- name: install desktop
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    #- ubuntu-desktop
    - ubuntu-mate-desktop
    - wmctrl
    - gnome-terminal

- name: mkdir .config 
  become: yes
  become_user: "{{ ubuntu_user }}"
  file: 
    path: /home/{{ ubuntu_user }}/.config
    state: directory
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
