- name: install desktop
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    #- ubuntu-desktop
    #- ubuntu-mate-desktop
    - ubuntu-mate-core
    - wmctrl
    - gnome-terminal

#- name: sh init-desktop.sh
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  shell: |
#    sh ~/.dotfiles/desktop/init-desktop.sh

- name: prepare for installing Canon MG7100 series driver
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    # canon scanner
    - sane
    - xsane
    - xsane-common
    - sane-utils
    - libsane
    - libsane-common
    - libsane-dbg
    - libsane-dev
    - libsane-extras
    - libsane-extras-common
    - libsane-extras-dbg
    - libsane-extras-dev
    - simple-scan
    - gimp

- apt_repository:
    repo: 'ppa:otto-kesselgulasch/gimp'
- apt_repository:
    repo: 'maarten-baert/simplescreenrecorder'
- name: install gui app
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    - goldendict
    - w3m
    - vlc
    - redshift
    - redshift-gtk
    - gimp
    - gimp-gmic
    - simplescreenrecorder
    - simplescreenrecorder-lib

- name: autologin
  become: yes
  become_user: root
  shell: |
    mkdir -p /usr/share/lightdm/lightdm.conf.d
    ln -sf /home/{{ ubuntu_user }}/.dotfiles/desktop/60-lightdm-gtk-greeter.conf /usr/share/lightdm/lightdm.conf.d/
    #mkdir -p /etc/lightdm/lightdm.conf.d
    #ln -sf /home/{{ ubuntu_user }}/.dotfiles/desktop/50-myconfig.conf /etc/lightdm/lightdm.conf.d/

- name: autostart
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    mkdir -p ~/.config/autostart
    ln -sf ~/.dotfiles/desktop/after-login.desktop ~/.config/autostart/after-login.desktop
    #sh ~/.dotfiles/desktop/start-up.sh
