- name: fzf
  become: true
  become_user: "{{ SUDO_USER }}"
  shell: |
    export PATH=$HOME/go/bin:$PATH
    ghq get https://github.com/junegunn/fzf.git
    $HOME/.ghq/github.com/junegunn/fzf/install

- name: dependencies for Dunst
  apt:
    update_cache: true
    name: "{{ item }}"
    state: latest
    autoclean: true
    autoremove: true
  with_items:
    - libdbus-1-dev
    - libx11-dev
    - libxinerama-dev
    - libxrandr-dev
    - libxss-dev
    - libglib2.0-dev
    - libpango1.0-dev
    - libgtk-3-dev
    - libxdg-basedir-dev
- name: dunst (notification)
  become: true
  become_user: "{{ SUDO_USER }}"
  shell: |
    export PATH=$HOME/go/bin:$PATH
    ghq get https://github.com/dunst-project/dunst.git
    cd $HOME/.ghq/github.com/dunst-project/dunst
    #sudo make
    sudo make install
    mvt /usr/local/share/dunst
    sudo ln -s "{{ HOME }}".config/dunst /usr/local/share/dunst
