- name: fzf
  become: true
  become_user: "{{ ubuntu_user }}"
  shell: |
    ghq get https://github.com/junegunn/fzf.git
    sh .ghq/github.com/junegunn/fzf/install

- name: dunst (notification)
  become: true
  become_user: "{{ ubuntu_user }}"
  shell: |
    ghq get https://github.com/dunst-project/dunst.git
    cd .ghq/github.com/dunst-project/dunst
    #sudo make
    sudo make install
