- name: dir for autologin 
  become: yes
  become_user: root
  file: 
    path: /etc/lightdm/lightdm.conf.d
    state: directory
    owner: root
    group: root
    #mode: 0777

- name: mkdir autostart 
  become: yes
  #become_user: root
  become_user: "{{ ubuntu_user }}"
  file: 
    path: /home/{{ ubuntu_user }}/.config/autostart
    state: directory
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
#    owner: root
#    group: root
#    mode: 0777

- name: clone dotfiles
  become: yes
  become_user: "{{ ubuntu_user }}"
  git:
    repo: https://github.com/enxajt/dotfiles.git
    dest: /home/{{ ubuntu_user }}/dotfiles
- name: symln dotfiles
  become: yes
  become_user: "{{ ubuntu_user }}"
  file:
    state: link
    src: /home/{{ ubuntu_user }}/dotfiles/.zshrc
    dest: /home/{{ ubuntu_user }}/.zshrc
- name: symln dotfiles
  become: yes
  become_user: "{{ ubuntu_user }}"
  file:
    state: link
    src: /home/{{ ubuntu_user }}/dotfiles/.tmux.conf
    dest: /home/{{ ubuntu_user }}/.tmux.conf
- name: symln dotfiles
  become: yes
  become_user: root
  file:
    state: link
    src: /home/{{ ubuntu_user }}/dotfiles/.Xresources
    dest: /etc/lightdm/lightdm.conf.d/.Xresources
- name: symln dotfiles
  become: yes
  become_user: root
  file:
    state: link
    src: /home/{{ ubuntu_user }}/dotfiles/50-myconfig.conf
    dest: /etc/lightdm/lightdm.conf.d/50-myconfig.conf
- name: symln dotfiles
  become: yes
  become_user: "{{ ubuntu_user }}"
  file:
    state: link
    src: /home/{{ ubuntu_user }}/dotfiles/gnome-terminal.desktop
    dest: /home/{{ ubuntu_user }}/.config/autostart/gnome-terminal.desktop
- name: sh /home/{{ ubuntu_user }}/dotfiles/init-ubuntu.sh
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    sh /home/"{{ ubuntu_user }}"/dotfiles/init-ubuntu.sh

#- git:
#    repo: https://github.com/enxajt/dotfiles.git
#    dest: /home/{{ ubuntu_user }}/dotfiles
#- file:
#    state: link
#    src: /home/{{ ubuntu_user }}/dotfiles/.zshrc
#    dest: /home/{{ ubuntu_user }}/.zshrc
#- file:
#    state: link
#    src: /home/{{ ubuntu_user }}/dotfiles/.tmux.conf
#    dest: /home/{{ ubuntu_user }}/.tmux.conf
#- file:
#    state: link
#    src: /home/{{ ubuntu_user }}/dotfiles/.Xresources
#    dest: /etc/lightdm/lightdm.conf.d/.Xresources
#- file:
#    state: link
#    src: /home/{{ ubuntu_user }}/dotfiles/50-myconfig.conf
#    dest: /etc/lightdm/lightdm.conf.d/50-myconfig.conf
#- file:
#    state: link
#    src: /home/{{ ubuntu_user }}/dotfiles/gnome-terminal.desktop
#    dest: /home/{{ ubuntu_user }}/.config/autostart/gnome-terminal.desktop

#- name: .zshrc, .tmux.conf, xterm, autologin, autostart
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  shell: |
#    [ -d /home/{{ ubuntu_user }}/dotfiles ] || git clone https://github.com/enxajt/dotfiles.git /home/"{{ ubuntu_user }}"/dotfiles
#    ln -s /home/"{{ ubuntu_user }}"/dotfiles/.zshrc /home/"{{ ubuntu_user }}"/.zshrc
#    ln -s /home/"{{ ubuntu_user }}"/dotfiles/.tmux.conf /home/"{{ ubuntu_user }}"/.tmux.conf

#- name: .zshrc, .tmux.conf, xterm, autologin, autostart
#  become: yes
#  become_user: root
#  shell: |
#    ln -s /home/"{{ ubuntu_user }}"/dotfiles/.Xresources /etc/lightdm/lightdm.conf.d/.Xresources
#    ln -s /home/"{{ ubuntu_user }}"/dotfiles/50-myconfig.conf /etc/lightdm/lightdm.conf.d/50-myconfig.conf
#    ln -s /home/"{{ ubuntu_user }}"/dotfiles/gnome-terminal.desktop /home/"{{ ubuntu_user }}"/.config/autostart/gnome-terminal.desktop
