- name: each user
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    [ ! -e ~/.dotfiles ] && git clone https://github.com/enxajt/.dotfiles.git ~/.dotfiles || echo already existing
    cd ~/.dotfiles && git remote set-url origin git@github.com:enxajt/.dotfiles.git
    sh ~/.dotfiles/init-ssh.sh
    sh ~/.dotfiles/install-neovim.sh
    ln -sf ~/.dotfiles/.zshrc ~/.zshrc
    [ ! -e ~/.zsh-git-prompt ] && git clone https://github.com/olivierverdier/zsh-git-prompt.git ~/.zsh-git-prompt || echo already existing
    ln -sf ~/.dotfiles/.tmux.conf ~/.tmux.conf
- name: new
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    mkdir -p ~/bin
    ln -s ~/.dotfiles/git-diff-normal-format ~/bin/
    chmod 777 bin/git-diff-normal-format
- name: root
  become: yes
  become_user: root
  shell: |
    mkdir -p /etc/lightdm/lightdm.conf.d
    ln -sf ~/.dotfiles/.Xresources /etc/lightdm/lightdm.conf.d/.Xresources
