- name: clone .dotfiles
  git:
    repo: git://github.com/enxajt/.dotfiles.git
    dest: /home/{{ ubuntu_user }}/.dotfiles 
    accept_hostkey: yes
- shell: |
    cd /home/{{ ubuntu_user }}/.dotfiles && git remote set-url origin git@github.com:enxajt/.dotfiles.git
- file:
    path: /home/{{ ubuntu_user }}/.dotfiles 
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    mode: 0777
    recurse: yes

- file:
    path: /home/{{ ubuntu_user }}/.tmux/plugins  
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/.tmux.conf
    dest: /home/{{ ubuntu_user }}/.tmux.conf
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/.tmux-bin
    dest: /home/{{ ubuntu_user }}/.tmux/bin
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- name: clone tmux-plubins
  git:
    repo: git://github.com/tmux-plugins/tpm.git
    dest: /home/{{ ubuntu_user }}/.tmux/plugins/tpm 
    accept_hostkey: yes

- file:
    path: /usr/share/lightdm/lightdm.conf.d
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/desktop/60-lightdm-gtk-greeter.conf
    dest: /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
    state: link
    force: yes
- file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/.Xresources
    dest: /etc/lightdm/lightdm.conf.d/.Xresources
    state: link

- user:
    name: "{{ ubuntu_user }}"
    shell: /bin/zsh
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/.zshrc
    dest: /home/{{ ubuntu_user }}/.zshrc
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- file:
    path: /home/{{ ubuntu_user }}/bin
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/git-diff-normal-format
    dest: /home/{{ ubuntu_user }}/bin/git-diff-normal-format
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
    mode: 0777

- name: clone zsh-git-prompt
  git:
    repo: git://github.com/olivierverdier/zsh-git-prompt.git
    dest: /home/{{ ubuntu_user }}/.zsh-git-prompt
    accept_hostkey: yes

- file:
    path: /home/{{ ubuntu_user }}/.config
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- name: termite
  file:
    src: /home/{{ ubuntu_user }}/.dotfiles/termite
    dest: /home/{{ ubuntu_user }}/.config/termite
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- name: clone .vim
  git:
    repo: git://github.com/enxajt/.vim.git
    dest: /home/{{ ubuntu_user }}/.vim
    accept_hostkey: yes
- shell: |
    cd /home/{{ ubuntu_user }}/.vim && git remote set-url origin git@github.com:enxajt/.vim.git
- file:
    path: /home/{{ ubuntu_user }}/.vim 
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    mode: 0777
    recurse: yes
- file:
    path: /home/{{ ubuntu_user }}/.config/nvim
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.vim/vimrc
    dest: /home/{{ ubuntu_user }}/.config/nvim/init.vim
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- file:
    src: /home/{{ ubuntu_user }}/.vim/dein.toml
    dest: /home/{{ ubuntu_user }}/.config/nvim/dein.toml
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- file:
    path: /home/{{ ubuntu_user }}/.config/i3
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- file:
    src: /home/{{ ubuntu_user }}/.dotfiles/i3-config
    dest: /home/{{ ubuntu_user }}/.config/i3/config
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
    force: yes

#- file:
#    src: /etc/systemd/logind.conf
#    dest: /etc/systemd/logind.conf.bak
#    force: yes
#- shell: |
#    echo HandleLidSwitch=ignore >> /etc/systemd/logind.conf
#    service systemd-logind restart
