- git:
    #repo: git://github.com/enxajt/.dotfiles.git
    repo: ssh://git@github.com/enxajt/.dotfiles.git
    dest: ~/.dotfiles 
    accept_hostkey: yes

- file:
    path: ~/.tmux/plugins  
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- file:
    src: ~/.dotfiles/.tmux.conf
    dest: ~/.tmux.conf
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- file:
    src: ~/.dotfiles/.tmux-bin
    dest: ~/.tmux/bin
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- git:
    repo: git://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm 
    accept_hostkey: yes

- name: sudo
  become: yes
  become_user: root
  shell: |
    mkdir -p /etc/lightdm/lightdm.conf.d
    ln -sf ~/.dotfiles/.Xresources /etc/lightdm/lightdm.conf.d/.Xresources

- user:
    name: "{{ ubuntu_user }}"
    shell: /bin/zsh
- file:
    src: ~/.dotfiles/.zshrc
    dest: ~/.zshrc
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- file:
    path: ~/bin
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: directory
- file:
    src: ~/.dotfiles/git-diff-normal-format
    dest: ~/bin/git-diff-normal-format
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
    mode: 0777

- git:
    repo: git://github.com/olivierverdier/zsh-git-prompt.git
    dest: ~/.zsh-git-prompt
    accept_hostkey: yes

- file:
    src: ~/.dotfiles/termite
    dest: ~/.config/termite
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

- git:
    #repo: git://github.com/enxajt/.vim.git
    repo: ssh://git@github.com/enxajt/.vim.git
    dest: ~/.vim
    accept_hostkey: yes
- file:
    src: ~/.vim/vimrc
    dest: ~/.config/nvim/init.vim
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
- file:
    src: ~/.vim/dein.toml
    dest: ~/.config/nvim/dein.toml
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link
