- name: user
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    [ ! -e ~/.dotfiles ] && git clone https://github.com/enxajt/.dotfiles.git ~/.dotfiles || echo already existing
    cd ~/.dotfiles && git remote set-url origin git@github.com:enxajt/.dotfiles.git && git pull
    # /vagrant/shared/ or git
    #ln -sf /vagrant/shared/.dotfiles ~/
    sh ~/.dotfiles/init-ssh.sh
    sh ~/.dotfiles/install-neovim.sh
- name: tmux
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    ln -sf ~/.dotfiles/.tmux.conf ~/.tmux.conf
    mkdir -p ~/.tmux/plugins  
    [ ! -e  ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm || echo already existing
    ln -sf ~/.dotfiles/.tmux-bin ~/.tmux/bin
- name: sudo
  become: yes
  become_user: root
  shell: |
    mkdir -p /etc/lightdm/lightdm.conf.d
    ln -sf ~/.dotfiles/.Xresources /etc/lightdm/lightdm.conf.d/.Xresources

- name: zsh
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    ln -sf ~/.dotfiles/.zshrc ~/.zshrc
    chsh -s /bin/zsh
- name: zsh-git-prompt
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    [ ! -e ~/.zsh-git-prompt ] && git clone https://github.com/olivierverdier/zsh-git-prompt.git ~/.zsh-git-prompt || echo already existing
    mkdir -p ~/bin
    ln -sf ~/.dotfiles/git-diff-normal-format ~/bin/
    chmod 777 ~/bin/git-diff-normal-format

#sudo apt-get install golang
#sudo mkdir -p ~/go
#echo "export GOPATH=$HOME/go" >> ~/.zshrc
#echo "export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin" >> ~/.zshrc
#go get github.com/peco/peco/cmd/peco
#go get github.com/motemen/ghq
#ghq get Shougo/dein.vim
