- name:
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    [ ! -e ~/.dotfiles ] && git clone https://github.com/enxajt/.dotfiles.git ~/.dotfiles
    sh ~/.dotfiles/init-ssh.sh
    sh ~/.dotfiles/install-vim.sh
    ln -sf ~/.dotfiles/.zshrc ~/.zshrc
    [ ! -e ~/.zsh-git-prompt ] && git clone https://github.com/olivierverdier/zsh-git-prompt.git ~/.zsh-git-prompt
    ln -sf ~/.dotfiles/.tmux.conf ~/.tmux.conf
    sudo ln -sf ~/.dotfiles/.Xresources /etc/lightdm/lightdm.conf.d/.Xresources
