- name: install desktop
  apt: name "{{item}}
  become: yes
  become_user: root
  with_items:
    #- ubuntu-desktop
    #- ubuntu-mate-desktop
    - ubuntu-mate-core

    - wmctrl

- name: natural scrolling
  file:
    src: /home/"{{ ubuntu_user }}".dotfiles/desktop/20-natural-scrolling.conf
    dest: /usr/share/X11/xorg.conf.d/20-natural-scrolling.conf
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    state: link

# for mate. not working in minimal ubuntu install
- name: autostart
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    mkdir -p ~/.config/autostart
    ln -sf ~/.dotfiles/desktop/after-login.desktop ~/.config/autostart/after-login.desktop
    #sh ~/.dotfiles/desktop/start-up.sh

    # background
    convert -size 500x500 xc:black ~/.black.jpg
    #export DISPLAY=:0.0
    #gsettings set org.mate.background picture-filename ~/.black.jpg
    dconf write /org/mate/desktop/background/picture-filename "'$HOME/.black.jpg'"
    #sleep 1 && rm ~/.black.jpg
    
    # desktop icon
    #gsettings set org.mate.caja.desktop home-icon-visible false
    #gsettings set org.mate.caja.desktop volumes-visible false
    dconf write /org/mate/caja/desktop/home-icon-visible false
    dconf write /org/mate/caja/desktop/volumes-visible false
    
    dconf write /org/mate/panel/toplevels/top/expand false
    dconf write /org/mate/panel/toplevels/top/auto-hide true
    dconf write /org/mate/panel/toplevels/top/size '21'
    
    dconf write /org/mate/screensaver/lock-enabled false
