---
#refer list in Japan
#- name: change mirror
#  become: yes
#  replace: |
#    dest=/etc/apt/sources.list
#    regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
#    replace=http://ftp.riken.go.jp/Linux/ubuntu\2
#  register: apt_mirror
#- name: apt update
#  become: yes
#  apt: update_cache=yes
#  when: apt_mirror|changed

# Windowsで作成した日本語を含むzipファイルを展開しても文字化けしないように
- name: add apt-key JapTeam package repository
  shell: wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | apt-key add -
- name: add apt-key JapTeam package repository
  shell: wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | apt-key add -
- name: add apt-key JapTeam package repository
  shell: wget https://www.ubuntulinux.jp/sources.list.d/trusty.list -O /etc/apt/sources.list.d/ubuntu-ja.list
- name: updates a server
  apt: update_cache=yes
- name: upgrade a server
  apt: upgrade=full
- name: install japanese
  apt: name={{item}}
  become: yes
  with_items:
    - ubuntu-defaults-ja # JapTeam package repository

- name: install japanese man
  apt: name={{item}}
  become: yes
  with_items: 
    - manpages-ja

- name: add-apt-repository ppa:japanese-testers/mozc
  shell: add-apt-repository ppa:japanese-testers/mozc
- name: updates a server
  apt: update_cache=yes
- name: upgrade a server
  apt: upgrade=full
- name: install japanese
  apt: name={{item}}
  become: yes
  with_items:
   - language-pack-ja-base
   - language-pack-ja
   #- ibus-mozc
   - fcitx-mozc
   - fcitx-libs-qt5
   - fcitx-frontend-qt5
   - im-setup-helper
   # sudo apt-get install -y language-pack-ja-base language-pack-ja
   # sudo apt-get install -y fcitx-libs-qt5 fcitx-frontend-qt5 im-setup-helper
   # fcitxと入力、表示されたFcitxセットアップヘルパーをクリックして起動する。
   # Ubuntuを再起動する。
   # mozcと入力、表示されたMozc の設定をクリックして起動
   # 「辞書」タブをクリック、「ユーザ辞書の編集...」ボタンをクリック、辞書ツールが起動
   # 「管理」ボタンをクリックして新規辞書にインポート...などから辞書ファイルを読み込む

# 初期設定ではキーボードの設定が一部リセットされる場合があるので設定を変更
- name: keyboard setting
  shell: gsettings set org.gnome.settings-daemon.plugins.keyboard active false

