- name: install nodejs, npm to install n
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - nodejs
    - npm

- name: install n
  shell: |
    sudo npm install n -g
    sudo n stable
    sudo apt purge -y nodejs npm
- name: confirm n installed
  shell: |
    exec $SHELL -l
    node -v

- name: install yarn
  shell: |
    sudo npm install --global yarn
