
- name: reduce waiting time for "A start job is running for raise network interfaces"
  shell: |
    systemctl disable systemd-networkd-wait-online.service
    systemctl mask systemd-networkd-wait-online.service
