- name: ubuntu
  remote_user: vagrant
  become: true
  hosts: 127.0.0.1
  connection: local
  vars:
    USER: enxajt
  tasks:
    - name: Hello.txt
      shell: echo Hello world! > hello.txt
