# apt refer in Japan
- name: change mirror
  replace: |
    dest=/etc/apt/sources.list
    regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
    replace=http://ftp.riken.go.jp/Linux/ubuntu\2
  register: apt_mirror
- name: apt update
  apt: update_cache=yes
  when: apt_mirror|changed

#- name: set locales for Terminal
#  shell: locale-gen en_US.UTF-8 ja_JP.UTF-8 en_AG.UTF-8 en_AU.UTF-8 en_BW.UTF-8 en_CA.UTF-8 en_DK.UTF-8 en_GB.UTF-8 en_HK.UTF-8 en_IE.UTF-8 en_IN.UTF-8 en_NG.UTF-8 en_NZ.UTF-8 en_PH.UTF-8 en_SG.UTF-8 en_ZA.UTF-8 en_ZM.UTF-8 en_ZW.UTF-8

#- name: set timezone
#  timezone:
#    #name: Europe/Paris
#    name: Japan
