- name:
  become: yes
  become_user: "{{ ubuntu_user }}"
  git:
    repo: https://github.com/Corwind/termite-install.git
    dest: "/home/{{ ubuntu_user }}/.cache/termite-install"
    force: yes

- name: termite settings
  become: yes
  become_user: root
  shell: |
    sh ./home/"{{ ubuntu_user }}"/.cache/termite-install/termite-install.sh
