- name: sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
  shell: |
    sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
    sed -ie 's/^#no_log = False/no_log = False/' /etc/ansible/ansible.cfg

- apt_repository:
    repo: "{{ item }}"
  with_items: 
    - 'ppa:hluk/copyq'
    - 'ppa:linrunner/tlp'
- name: apt install
  apt:
    update_cache: true
    name: "{{ item }}"
    state: latest
    autoclean: true
    autoremove: true
  with_items:
    #- aptitude
    - xbindkeys

    - git
    - zsh
    - tree
    - unar

    - sysstat
    - duc

    - p7zip-full #7z
    - p7zip-rar

    - nkf
    - colordiff
    - pandoc
    - xsel
    - copyq

    - vim
    - jq

    - x11-xserver-utils
    - powertop 
    - tlp 
    - tlp-rdw

    - w3m
    - w3m-img

    - clamav
    - chkrootkit

    # for local machine : hard ware
    - xbacklight
    - pulseaudio
    - pavucontrol
    # for local machine : drive
    - exfat-fuse
    - exfat-utils
    # for local machine : network
    - linux-generic-hwe-16.04
    - connect-proxy
    - lshw
    - wicd
    - intel-microcode
    # not for virtualmachine
    - vagrant
    - virtualbox

    - pdftk

    - fonts-ricty-diminished 
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho
- name: init clamav 
  become: true
  shell: | 
    sed -i -e "s/^NotifyClamd/#NotifyClamd/g" /etc/clamav/freshclam.conf
    systemctl stop clamav-freshclam
    freshclam
    systemctl start clamav-freshclam

- name: init sh 
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/enxajt/init.git
    dest: /home/{{ ubuntu_user }}/init
- name: git remote set-url origin git@github.com:enxajt/init.git
  shell: |
    cd /home/{{ ubuntu_user }}/init && git remote set-url origin git@github.com:enxajt/init.git
- name: init sh 
  become: true
  become_user: "{{ ubuntu_user }}" 
  shell: | 
    sh /home/{{ ubuntu_user }}/init/install-tmux.sh
    sh /home/{{ ubuntu_user }}/init/install-neovim.sh 
    #sh /home/{{ ubuntu_user }}/init/install-npm.sh 

- name: install Dropbox
  become: yes
  #become_user: root
  become_user: "{{ ubuntu_user }}"
  shell: |
    cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
- name: install Dropbox tool
  become: yes
  become_user: root
  shell: |
    wget -O /usr/bin/dropbox "http://www.dropbox.com/download?dl=packages/dropbox.py"
    chmod a+x /usr/bin/dropbox

- name: install Dropbox tool
  become: yes
  become_user: root
  shell: |
    wget http://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar -O /usr/local/bin/BFG_git-repo-cleaner.jar

- name: git config
  become: yes
  become_user: "{{ ubuntu_user }}" 
  shell: |
  git config --global user.email "{{ ubuntu_user }}@gmail.com"
  git config --global user.name "{{ ubuntu_user }}"

- name: Bluetooth
  become: yes
  become_user: root
  shell: |
    #sed -ie 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf
    apt-get install bluez-tools
    systemctl start bluetooth
    systemctl enable bluetooth
