- name: sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
  shell: |
    sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
    sed -ie 's/^#no_log = False/no_log = False/' /etc/ansible/ansible.cfg

- apt_repository:
    repo: "{{ item }}"
  with_items: 
    - ppa:hluk/copyq
    - ppa:linrunner/tlp
- name: apt install
  apt:
    update_cache: true
    name: "{{ item }}"
    state: latest
    autoclean: true
    autoremove: true
  with_items:
    #- aptitude
    - xbindkeys

    - git
    - zsh
    - tree
    - unar

    - sysstat
    - duc

    - p7zip-full #7z
    - p7zip-rar

    - nkf
    - colordiff
    - vim
    - pandoc
    - xsel
    - copyq

    - x11-xserver-utils
    - powertop 
    - tlp 
    - tlp-rdw

    - w3m
    - w3m-img

    - clamav
    - chkrootkit

    # for local machine : hard ware
    - xbacklight
    # for local machine : drive
    - exfat-fuse
    - exfat-utils
    # for local machine : network
    - linux-generic-hwe-16.04
    - connect-proxy
    - lshw
    - wicd
    - intel-microcode
    # not for virtualmachine
    - vagrant
    - virtualbox

    - fonts-ricty-diminished 
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho
- name: init clamav 
  become: true
  shell: | 
    sed -i -e "s/^NotifyClamd/#NotifyClamd/g" /etc/clamav/freshclam.conf
    freshclam 

- name: init sh 
  become: true
  become_user: "{{ ubuntu_user }}" 
  git:
    repo: git://github.com/enxajt/init.git
    dest: /home/{{ ubuntu_user }}/init
- name: git remote set-url origin git@github.com:enxajt/init.git
  shell: |
    cd /home/{{ ubuntu_user }}/init && git remote set-url origin git@github.com:enxajt/init.git
- name: init sh 
  become: true
  become_user: "{{ ubuntu_user }}" 
  shell: | 
    sh /home/{{ ubuntu_user }}/init/install-tmux.sh
    sh /home/{{ ubuntu_user }}/init/install-neovim.sh 
    sh /home/{{ ubuntu_user }}/init/init-xdg.sh
    sh /home/{{ ubuntu_user }}/init/install-npm.sh 
