---
- name: updates a server
  apt: update_cache=yes

- name: install aptitude
  apt: name=aptitude
  become: yes
- name: upgrade a server
  apt: upgrade=full

- name: install tools
  apt: name={{item}}
  become: yes
  with_items:
    - zsh
    - nkf
    - tmux
    - colordiff
    - xsel
    - pandoc
    - clamav
    - chkrootkit
    - xbindkeys
    - unar
    - tree

    # for local machine
    - connect-proxy
    - exfat-fuse
    - exfat-utils

    # not for virtualmachine
    - vagrant
    - virtualbox

    #- fonts-ricty-diminished 
    #- fonts-ipafont-gothic
    #- fonts-ipafont-mincho
