- name: sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
  shell: |
    sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
    sed -ie 's/^#no_log = False/no_log = False/' /etc/ansible/ansible.cfg

- apt_repository:
    repo: "{{ item }}"
  with_items: 
    - 'ppa:hluk/copyq'
    - 'ppa:linrunner/tlp'

# https://skalldan.wordpress.com/2011/09/02/ubuntu-%E3%81%A7%E8%BB%BD%E9%87%8F%E3%81%AE%E7%94%BB%E5%83%8F%E3%83%93%E3%83%A5%E3%83%BC%E3%82%A2-feh-%E3%82%92%E4%BD%BF%E3%81%86/
# apt-get install libcurl4-openssl-dev libx11-dev libxt-dev libimlib2-dev libxinerama-dev libjpeg-progs
# wget -O - 'http://feh.finalrewind.org/feh-2.27.1.tar.bz2' | tar xjf -
# cd feh-2.27.1
# make
# sudo make install


- name: apt install
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - xbindkeys

    - wget
    - curl
    - git
    - zsh
    - tree

    - unar # or atool

    #- sysstat
    #- duc

    #- p7zip-full #7z
    #- p7zip-rar

    #- nkf
    - colordiff
    #- pandoc
    - xsel
    #- copyq

    - vim
    #- jq
    #- pdftk

    #- w3m
    #- w3m-img

    # # for local machine : hard ware
    # - xbacklight
    # - pulseaudio
    # - pavucontrol
    # - x11-xserver-utils
    # - powertop 
    # - tlp 
    # - tlp-rdw
    # # for local machine : drive
    # - exfat-fuse
    # - exfat-utils

    # for local machine : network
    - linux-generic-hwe-16.04
    - connect-proxy
    - lshw
    - wicd
    - intel-microcode

    # # not for virtualmachine
    # - vagrant
    # - virtualbox

    - fonts-ricty-diminished 
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho

- name: git config
  become: yes
  become_user: "{{ ubuntu_user }}" 
  shell: |
    git config --global user.email "{{ git_email }}"
    git config --global user.name "{{ git_user }}"
    git config --global core.editor "vim"
    git config --global merge.tool vimdiff
    git config --global push.default simple
