- name: sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
  shell: |
    sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
    sed -ie 's/^#no_log = False/no_log = False/' /etc/ansible/ansible.cfg

- apt_repository:
    repo: "{{ item }}"
  with_items: 
    - 'ppa:hluk/copyq'
    - 'ppa:linrunner/tlp'
- name: apt install
  apt:
    update_cache: true
    name: "{{ item }}"
    state: latest
    autoclean: true
    autoremove: true
  with_items:
    #- aptitude
    - xbindkeys

    # for gui termite
    - gtk-doc-tools

    - wget
    - curl
    - git
    - zsh
    - tree
    - unar

    - sysstat
    - duc

    - p7zip-full #7z
    - p7zip-rar

    - nkf
    - colordiff
    - pandoc
    - xsel
    - copyq

    - vim
    - jq

    - w3m
    - w3m-img

    - clamav
    - chkrootkit

    # for local machine : hard ware
    - xbacklight
    - pulseaudio
    - pavucontrol
    - x11-xserver-utils
    - powertop 
    - tlp 
    - tlp-rdw
    # for local machine : drive
    - exfat-fuse
    - exfat-utils
    # for local machine : network
    - linux-generic-hwe-16.04
    - connect-proxy
    - lshw
    - wicd
    - intel-microcode
    # not for virtualmachine
    - vagrant
    - virtualbox

    - pdftk

    - fonts-ricty-diminished 
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho
- name: init clamav 
  become: true
  shell: | 
    sed -i -e "s/^NotifyClamd/#NotifyClamd/g" /etc/clamav/freshclam.conf
    systemctl stop clamav-freshclam
    freshclam
    systemctl start clamav-freshclam

- name: install Dropbox
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
- name: install Dropbox tool
  become: yes
  become_user: root
  shell: |
    wget -O /usr/bin/dropbox "http://www.dropbox.com/download?dl=packages/dropbox.py"
    chmod a+x /usr/bin/dropbox
    wget http://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar -O /usr/local/bin/BFG_git-repo-cleaner.jar

- name: git config
  become: yes
  become_user: "{{ ubuntu_user }}" 
  shell: |
    git config --global user.email "{{ git_email }}"
    git config --global user.name "{{ git_user }}"
    git config --global core.editor "vim"
