#- name: ansible log on
#  shell: |
#    sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
#    sed -ie 's/^#no_log = False/no_log = False/' /etc/ansible/ansible.cfg
#
#- name: configure the repository to install yarn
#  shell: |
#    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
#    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

- apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:git-core/ppa'
- name: apt install
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zsh
    - xbindkeys

    - wget
    - curl
    - git
    - tree
    - vim
    - neovim
    - yarn
    - tmux

    - unar # or atool
    #- p7zip-full #7z
    #- p7zip-rar

    - nkf
    - colordiff
    - xsel
    - jq
    - duc #disk usege visualize
