- name: updates a server
  apt: update_cache=yes
- name: install aptitude
  apt: name=aptitude
  become: yes
- name: upgrade a server
  apt: upgrade=full

- name: install tools
  apt: name={{item}}
  become: yes
  with_items:
    # wifi
    - linux-generic-hwe-16.04
    #- linux-generic-hwe-16.04-edge
    #-r8168-dkms
    
    - git

    - zsh
    - xbindkeys
    - colordiff
    - tree
    - nkf
    - xsel
    - pandoc
    - unar
    - p7zip-full #7z
    - p7zip-rar
    - sysstat

    - clamav
    - chkrootkit

    # for local machine : drive
    - exfat-fuse
    - exfat-utils

    # for local machine : network
    - connect-proxy
    - lshw
    - wicd
    - intel-microcode

    # not for virtualmachine
    - vagrant
    - virtualbox

    #- fonts-ricty-diminished 
    #- fonts-ipafont-gothic
    #- fonts-ipafont-mincho

- git:
    repo: git://github.com/enxajt/init.git
    dest: ~/init
- name: init sh
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    sh ~/init/install-vagrant.sh
    sh ~/init/install-tmux.sh
    sh ~/init/install-neovim.sh
