- name: ansible log on
  shell: |
    sed -ie 's/^#log_path/log_path/' /etc/ansible/ansible.cfg
    sed -ie 's/^#no_log = False/no_log = False/' /etc/ansible/ansible.cfg

- name: apt install
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zsh
    - xbindkeys

    - wget
    - curl
    - git
    - tree
    - vim

    - ranger
    - w3m
    - w3m-img

    - unar # or atool
    #- p7zip-full #7z
    #- p7zip-rar

    - nkf
    - colordiff
    - xsel
    - jq
    - duc #disk usege visualize

- name: git config
  become: yes
  become_user: "{{ ubuntu_user }}" 
  shell: |
    git config --global user.email "{{ git_email }}"
    git config --global user.name "{{ git_user }}"
    git config --global core.editor "vim"
    git config --global merge.tool vimdiff
    git config --global push.default simple
