- apt_repository:
    repo: 'ppa:linrunner/tlp'
- name: updates a server
  apt: update_cache=yes
- name: install aptitude
  apt: name=aptitude
- name: upgrade a server
  apt: upgrade=full
- name: install tools
  apt: name={{item}}
  become: yes
  with_items:
    # wifi
    - linux-generic-hwe-16.04
    #- linux-generic-hwe-16.04-edge
    #-r8168-dkms
    
    - git

    - zsh
    - xbindkeys
    - colordiff
    - tree
    - nkf
    - xsel
    - pandoc
    - unar
    - p7zip-full #7z
    - p7zip-rar
    - sysstat

    - powertop 
    - tlp 
    - tlp-rdw

    - w3m
    - w3m-img

    - clamav
    - chkrootkit

    # for local machine : hard ware
    - xbacklight
    # for local machine : drive
    - exfat-fuse
    - exfat-utils
    # for local machine : network
    - connect-proxy
    - lshw
    - wicd
    - intel-microcode

    # not for virtualmachine
    - vagrant
    - virtualbox

    #- fonts-ricty-diminished 
    #- fonts-ipafont-gothic
    #- fonts-ipafont-mincho
- shell: |
    cp /etc/default/sysstat /etc/default/sysstat.bak
    sed -ie 's/^ENABLED="false"$/ENABLED="true"/' /etc/default/sysstat
    /etc/init.d/sysstat start
    wget https://sourceforge.net/projects/ksar/files/latest/download -O /usr/local/src/ksar.zip
    unzip /usr/local/src/ksar.zip -d /usr/local/src
- shell: |
    powertop --calibrate
    powertop --auto-tune
    tlp start
- git:
    repo: git://github.com/enxajt/init.git
    dest: /home/{{ ubuntu_user }}/init
- shell: |
    cd /home/{{ ubuntu_user }}/init && git remote set-url origin git@github.com:enxajt/init.git
- file:
    path: /home/{{ ubuntu_user }}/init
    owner: "{{ ubuntu_user }}"
    group: "{{ ubuntu_user }}"
    mode: 0777
    recurse: yes
- name: init sh
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    sh ~/init/install-vagrant.sh
    sh ~/init/install-tmux.sh
    sh ~/init/install-neovim.sh
