- name: install Git 
  apt: name={{item}}
  become: yes
  become_user: "{ubuntu_user}"
  with_items:
    - git
- git_config:
    name: user.name
    scope: global
    value: 'enxajt' 
- git_config:
    name: user.email
    scope: global
    value: 'enxajt@gmail.com' 
