- name: updates a server
  apt: update_cache=yes
- name: upgrade a server
  apt: upgrade=full

- name: prepare installing docker (not ansible-apt)
  shell: apt-get -y install linux-image-extra-$(uname -r)

- name: install for docker 
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    - linux-image-extra-virtual
    - apt-transport-https 
    - ca-certificates

- name: add-apt-repository ppa:japanese-testers/mozc
  shell: |
    curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
    add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"

- name: updates a server
  apt: update_cache=yes
- name: install docker-engine
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    - docker-engine

- name: add {{ ubuntu_user }} to Docker group
  become: yes
  become_user: root
  shell: usermod -aG docker "{{ ubuntu_user }}"

- name: docker-compose install
  become: yes
  become_user: root
  shell: |
    curl -L https://github.com/docker/compose/releases/download/1.11.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

#- name: mv docker directory
#  become: yes
#  become_user: root
#  shell: |
#    systemctl stop docker
#    #service docker stop
#    [ -d {{ docker_root }} ] && rm -rf /var/lib/docker
#    [ -d /var/lib/docker ] && mv /var/lib/docker "{{ docker_root }}"
#    #ln -s "{{ docker_root }}" /var/lib/docker
#    sed -ie "s/^\(ExecStart=\/usr\/bin\/dockerd -H fd:\/\/\)/\1 -g {{ docker_root }}/g" /lib/systemd/system/docker.service
#    systemctl daemon-reload
#    systemctl start docker 
#    #sudo service docker start
