- apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:canonical-chromium-builds/stage'
    - 'ppa:font-manager/staging'
- name: install gui app
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - thunar # or Nemo, ranger, vim, spacefm,
    - font-manager
    - redshift
    - shutter

    - i3
    - compton
    - i3blocks
    - rofi

    - terminator
    - rxvt-unicode
    - chromium-browser
    - firefox
    - flashplugin-installer
    - zathura

    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    - ubuntu-drivers-common
    - mesa-utils
    - mesa-utils-extra
    - xorg
    - xserver-xorg
    - volumeicon-alsa

- lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: sed wlp for i3 statusbar
  shell: |
    WLP=`ip addr show | grep wlp | awk '/inet.*brd/{print $NF}'`; sed -i "s/test/$WLP/g" /home/{{ ubuntu_user }}/.config/i3blocks/config

- name: Clone termite-install.git
  become: yes
  become_user: "{{ ubuntu_user }}"
  git:
    repo: https://github.com/Corwind/termite-install.git
    dest: "/home/{{ ubuntu_user }}/.cache/termite-install"
    force: yes
- name: Install Termite
  become: yes
  become_user: root
  shell: |
    sh /home/"{{ ubuntu_user }}"/.cache/termite-install/termite-install.sh
