- name: prepare for installing Canon MG7100 series driver
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    # canon scanner
    - sane
    - xsane
    - xsane-common
    - sane-utils
    - libsane
    - libsane-common
    - libsane-dbg
    - libsane-dev
    - libsane-extras
    - libsane-extras-common
    - libsane-extras-dbg
    - libsane-extras-dev
    - simple-scan
    - gimp

- apt_repository:
    repo: 'ppa:otto-kesselgulasch/gimp'
#- apt_repository:
#    repo: 'maarten-baert/simplescreenrecorder'
- name: install gui app
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    - gimp
    - gimp-gmic
    - goldendict
    - redshift
    - redshift-gtk
    - vlc
    - w3m
    - wmctrl
    - i3
#    - simplescreenrecorder
#    - simplescreenrecorder-lib

- git:
    repo: https://github.com/Corwind/termite-install.git
    dest: ~/

- name: user
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    ~/termite-install/termite-install.sh
