- name: prepare for installing Canon MG7100 series driver
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    # canon scanner
    - sane
    - xsane
    - xsane-common
    - sane-utils
    - libsane
    - libsane-common
    - libsane-dbg
    - libsane-dev
    - libsane-extras
    - libsane-extras-common
    - libsane-extras-dbg
    - libsane-extras-dev
    - simple-scan
    - gimp

- apt_repository:
    repo: 'ppa:otto-kesselgulasch/gimp'
#- apt_repository:
#    repo: 'maarten-baert/simplescreenrecorder'
- name: install gui app
  apt: name={{item}}
  become: yes
  become_user: root
  with_items:
    - goldendict
    - w3m
    - vlc
    - redshift
    - redshift-gtk
    - gimp
    - gimp-gmic
#    - simplescreenrecorder
#    - simplescreenrecorder-lib
