- apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:canonical-chromium-builds/stage'
    - 'ppa:otto-kesselgulasch/gimp'
    - 'ppa:font-manager/staging'
    - 'ppa:libreoffice/libreoffice-5-4'
- name: install gui app
  apt:
    name: "{{ packages }}"
    update_cache: yes
    upgrade: safe
  vars:
    packages:
    - chromium-browser
    - gimp
    - gimp-gmic
    - libreoffice
    - font-manager

    - firefox
    - flashplugin-installer
    - goldendict
    - redshift

    - shutter
    - vlc
    - freeplane

    - playonlinux

    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    - i3
    - compton
    - i3blocks
    - rofi

    - ubuntu-drivers-common
    - mesa-utils
    - mesa-utils-extra
    - xorg
    - xserver-xorg
    - thunar
    - volumeicon-alsa

#- apt_repository:
#    repo: 'maarten-baert/simplescreenrecorder'
#- name: install gui app
#  apt: name={{item}}
#  with_items:
#    - simplescreenrecorder
#    - simplescreenrecorder-lib

- lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

#- name: termite apt-get
#  apt:
#    name: "{{ item }}"
#    update_cache: yes
#    upgrade: full
#  with_items:
#    - g++
#    - libgtk-3-dev
#    - gtk-doc-tools
#    - gnutls-bin
#    - valac
#    - intltool
#    - libpcre2-dev
#    - libglib3.0-cil-dev
#    - libgnutls28-dev
#    - libgirepository1.0-dev
#    - libxml2-utils
#    - gperf
#- name: termite vte-ng clone
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  git:
#    repo: https://github.com/thestinger/vte-ng.git
#    dest: "/home/{{ ubuntu_user }}/.cache/vte-ng"
#    force: yes
#- name: termite clone
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  git:
#    repo: https://github.com/thestinger/termite.git
#    dest: "/home/{{ ubuntu_user }}/.cache/termite"
#    force: yes
#    recursive: yes
#- name: termite vte-ng & termite install prepare
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  shell: |
#    echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"
#    cd /home/"{{ ubuntu_user }}"/.cache/vte-ng && ./autogen.sh && make
#    cd /home/{{ ubuntu_user }}/.cache/termite && make
#- name: termite settings
#  become: yes
#  become_user: root
#  shell: |
#    cd /home/"{{ ubuntu_user }}"/.cache/vte-ng && make install
#    cd /home/{{ ubuntu_user }}/.cache/termite && make install
#    ldconfig
#    mkdir -p /lib/terminfo/x
#    ln -s /usr/local/share/terminfo/x/xterm-termite /lib/terminfo/x/xterm-termite
#    update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/termite 60
