- apt_repository:
    repo: "{{ item }}"
  with_items: 
    - 'ppa:canonical-chromium-builds/stage'
    - 'ppa:otto-kesselgulasch/gimp'
    - 'ppa:font-manager/staging'
    - 'ppa:libreoffice/libreoffice-5-4'
- name: updates a server
  apt: update_cache=yes
- name: upgrade a server
  apt: upgrade=full
- name: install gui app
  apt: name={{item}}
  with_items:
    - chromium-browser
    - gimp
    - gimp-gmic
    - libreoffice
    - font-manager

    - firefox
    - flashplugin-installer
    - goldendict
    - redshift

    - shutter
    - vlc
    - freeplane

    - playonlinux

    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    - i3
    - compton
    - i3blocks
    - rofi

    - ubuntu-drivers-common
    - mesa-utils
    - mesa-utils-extra
    - xorg
    - xserver-xorg
    - thunar
    - volumeicon-alsa

#- apt_repository:
#    repo: 'maarten-baert/simplescreenrecorder'
#- name: install gui app
#  apt: name={{item}}
#  with_items:
#    - simplescreenrecorder
#    - simplescreenrecorder-lib

- lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: which termite 
  shell: which termite
  register: which_termite
  failed_when: which_termite.rc not in [0, 1]
- name: for termite
  when: which_termite.stdout == ""
  apt: name={{item}}
  with_items:
    - g++
    - libgtk-3-dev
    - gtk-doc-tools
    - gnutls-bin
    - valac
    - intltool
    - libpcre2-dev
    - libglib3.0-cil-dev
    - libgnutls28-dev
    - libgirepository1.0-dev
    - libxml2-utils
    - gperf
- name: vte-ng
  when: which_termite.stdout == ""
  become: yes
  become_user: "{{ ubuntu_user }}"
  git:
    repo: https://github.com/thestinger/vte-ng.git
    dest: /home/{{ ubuntu_user }}/.cache/vte-ng
    force: yes
- name: vte-ng
  when: which_termite.stdout == ""
  become: yes
  become_user: "{{ ubuntu_user }}"
  git:
    repo: https://github.com/thestinger/termite.git
    dest: /home/{{ ubuntu_user }}/.cache/termite
    force: yes
- name: user
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"
    cd /home/{{ ubuntu_user }}/.cache/vte-ng && ./autogen.sh && make && sudo make install
    cd /home/{{ ubuntu_user }}/.cache/termite && make && sudo make install
  when: which_termite.stdout == ""
- name: user
  become: yes
  become_user: root
  shell: |
    ldconfig
    mkdir -p /lib/terminfo/x
    ln -s /usr/local/share/terminfo/x/xterm-termite /lib/terminfo/x/xterm-termite
  when: which_termite.stdout == ""
