- apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:canonical-chromium-builds/stage'
    - 'ppa:font-manager/staging'
- name: install gui app
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - chromium-browser
    - font-manager
    - firefox
    - flashplugin-installer
    - redshift
    - shutter

    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    - i3
    - compton
    - i3blocks
    - rofi

    - ubuntu-drivers-common
    - mesa-utils
    - mesa-utils-extra
    - xorg
    - xserver-xorg
    - thunar
    - volumeicon-alsa

- lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

#- name: termite apt-get
#  apt:
#    name: "{{ item }}"
#    update_cache: yes
#    upgrade: full
#  with_items:
#    - g++
#    - libgtk-3-dev
#    - gtk-doc-tools
#    - gnutls-bin
#    - valac
#    - intltool
#    - libpcre2-dev
#    - libglib3.0-cil-dev
#    - libgnutls28-dev
#    - libgirepository1.0-dev
#    - libxml2-utils
#    - gperf
#- name: termite vte-ng clone
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  git:
#    repo: https://github.com/thestinger/vte-ng.git
#    dest: "/home/{{ ubuntu_user }}/.cache/vte-ng"
#    force: yes
#- name: termite clone
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  git:
#    repo: https://github.com/thestinger/termite.git
#    dest: "/home/{{ ubuntu_user }}/.cache/termite"
#    force: yes
#    recursive: yes
#- name: termite vte-ng & termite install prepare
#  become: yes
#  become_user: "{{ ubuntu_user }}"
#  shell: |
#    echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"
#    cd /home/"{{ ubuntu_user }}"/.cache/vte-ng && ./autogen.sh && make
#    cd /home/{{ ubuntu_user }}/.cache/termite && make
#- name: termite settings
#  become: yes
#  become_user: root
#  shell: |
#    cd /home/"{{ ubuntu_user }}"/.cache/vte-ng && make install
#    cd /home/{{ ubuntu_user }}/.cache/termite && make install
#    ldconfig
#    mkdir -p /lib/terminfo/x
#    ln -s /usr/local/share/terminfo/x/xterm-termite /lib/terminfo/x/xterm-termite
#    update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/termite 60

- name: xfce4-terminal download
  get_url:
    url: http://archive.xfce.org/src/apps/xfce4-terminal/0.8/xfce4-terminal-0.8.7.4.tar.bz2
    dest: /home/{{ ubuntu_user }}/.cache/xfce4-terminal-0.8.7.4.tar.bz2
    mode: 0755
- name: xfce4-terminal configure & make
  become: yes
  become_user: "{{ ubuntu_user }}"
  shell: |
    cd /home/{{ ubuntu_user }}/.cache/ && unar xfce4-terminal-0.8.7.4.tar.bz2
    cd /home/{{ ubuntu_user }}/.cache/xfce4-terminal-0.8.7.4 && ./configure --prefix=/usr && make
- name: xfce4-terminal install
  become: yes
  become_user: root
  shell: |
    make install
