---
#refer list in Japan
#- name: change mirror
#  become: yes
#  replace: |
#    dest=/etc/apt/sources.list
#    regexp=http://(archive|security)\.ubuntu\.com/ubuntu(.+)
#    replace=http://ftp.riken.go.jp/Linux/ubuntu\2
#  register: apt_mirror
#- name: apt update
#  become: yes
#  apt: update_cache=yes
#  when: apt_mirror|changed

#- locale_gen:
#    name: en_US.UTF-8

- name: set locales for Terminal
  shell: locale-gen en_US.UTF-8 ja_JP.UTF-8 en_AG.UTF-8 en_AU.UTF-8 en_BW.UTF-8 en_CA.UTF-8 en_DK.UTF-8 en_GB.UTF-8 en_HK.UTF-8 en_IE.UTF-8 en_IN.UTF-8 en_NG.UTF-8 en_NZ.UTF-8 en_PH.UTF-8 en_SG.UTF-8 en_ZA.UTF-8 en_ZM.UTF-8 en_ZW.UTF-8

- name: set timezone
  timezone:
    name: Europe/Paris

- name: install aptitude
  apt: name=aptitude
  become: yes

- name: add apt-key JapTeam package repository
  shell: wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | apt-key add -
- name: add apt-key JapTeam package repository
  shell: wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | apt-key add -
- name: add apt-key JapTeam package repository
  shell: wget https://www.ubuntulinux.jp/sources.list.d/trusty.list -O /etc/apt/sources.list.d/ubuntu-ja.list

- name: updates a server
  apt: update_cache=yes
- name: upgrade a server
  apt: upgrade=full

- name: install japanese
  apt: name={{item}}
  become: yes
  with_items: 
    #- language-pack-ja-base
    #- language-pack-ja
    #- ibus-mozc
    - manpages-ja
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho

- name: install japanese
  apt: name={{item}}
  become: yes
  with_items:
    - ubuntu-defaults-ja # JapTeam package repository
    - fcitx-mozc
    - fcitx-libs-qt5
    - fcitx-frontend-qt5
    - im-setup-helper
    # fcitxと入力、表示されたFcitxセットアップヘルパーをクリックして起動する。
    # ダイアログが表示され、Fcitxをデフォルトにする設定を行いますか？
    #「はい」ボタンをクリック、「OK」ボタンをクリックして設定を終了
    # Ubuntuを再起動する。
    # mozcと入力、表示されたMozc の設定をクリックして起動
    # 「辞書」タブをクリック、「ユーザ辞書の編集...」ボタンをクリック、辞書ツールが起動
    # 「管理」ボタンをクリックして新規辞書にインポート...などから辞書ファイルを読み込む

- name: install tools
  apt: name={{item}}
  become: yes
  with_items:
    #- language-pack-ja
    - nkf
    - rsplib-legacy-wrappers # Terminal
    - virtualbox-guest-dkms

- name: install zsh
  apt: name={{item}}
  become: yes
  with_items:
    - zsh
- name: get zshrc
  get_url:
    url: https://raw.githubusercontent.com/enxajt/zsh/master/.zshrc
    dest: ~/.zshrc
- name: chsh to zsh
  shell: chsh -s /bin/zsh

- name: mkdir kohei-dev
  file: path=~/kohei-dev state=directory owner=root group=root mode=0777
- name: get Dockerfile
  get_url:
    url: https://raw.githubusercontent.com/enxajt/dockerfiles/master/vim-ubuntu/Dockerfile
    dest: ~/kohei-dev/Dockerfile 
- name: nkf Dockerfile
  shell: nkf -w -Lu --overwrite ~/kohei-dev/Dockerfile

- git_config:
    name: user.name
    scope: global
    value: 'enxajt' 
- git_config:
    name: user.email
    scope: global
    value: 'enxajt@gmail.com' 

############################################################################
### heavy 
- name: install ubuntu-desktop
  apt: name={{item}}
  become: yes
  with_items:
    - ubuntu-desktop
