- name: after zshrc, prepare to install go
  file:
    state: directory
    path: '{{ item }}'
    owner: "{{ SUDO_USER }}" 
    group: "{{ SUDO_USER }}" 
    mode: 0777 
    recurse: true
  with_items:
    - {{ HOME }}/.cache
    - {{ HOME }}/go

- name: install go
  become: true
  shell: |
    wget -O - https://dl.google.com/go/go1.9.3.linux-amd64.tar.gz | tar -xzf - -C /usr/local
- name: go get ghq
  become: true
  become_user: "{{ SUDO_USER }}"
  shell: |
    export PATH=$PATH:/usr/local/go/bin
    go get github.com/motemen/ghq
