- name: add-apt-repository ppa:japanese-testers/mozc
  shell: add-apt-repository ppa:japanese-testers/mozc
- name: updates a server
  apt: update_cache=yes

- name: install japanese
  apt: name "{{item}}
  become: yes
  with_items:
   - language-pack-ja-base
   - language-pack-ja
   - fcitx
   - fcitx-mozc
   - fcitx-libs-qt5
   - fcitx-frontend-qt5
   - mozc-utils-gui

- name: im-config -n fcitx
  shell: im-config -n fcitx

- name: purge ibus
  apt:
    name: ibus
    state: absent
    purge: yes
