- apt_repository:
    repo: "{{ repos }}"
  vars:
    repos:
    - 'ppa:japanese-testers/mozc'
- name: install japanese
  become: yes', 
  apt: 
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - language-pack-ja-base
    - language-pack-ja
    - fcitx
    - fcitx-mozc
    - libfcitx-qt5-1
    - fcitx-frontend-qt5
    - mozc-utils-gui

    - fonts-ricty-diminished 
    - fonts-takao*
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho

- name: im-config -n fcitx
  shell: im-config -n fcitx

- name: purge ibus
  apt:
    name: ibus
    state: absent
    purge: yes
